### ISSUE TITLE
Redis Sentinel set passwords

### ISSUE THREAD

**Issue by phlegx** [anycable/anycable-go#105]
Hi there!

For `anycable-go` `1.0.0`, how can I set/pass a password for the Sentinels in ENV var

```ANYCABLE_REDIS_SENTINELS=127.0.0.1:26380,127.0.0.1:26381```

or is this maybe not possible yet?

Thank you in advance
Martin

**Comment by palkan** [comment]
> is this maybe not possible yet?

Correct.

I think, we can add passwords support and allow providing them using the following format:

```
ANYCABLE_REDIS_SENTINELS=:password1@127.0.0.1:26380,:password2@127.0.0.1:26381
```

And then we can use `url.Parse()` to extract this information: https://play.golang.org/p/tZp7d377Xpc

@rolandg Would you be interested in adding this enhancement?

**Comment by palkan** [comment]
Released in 1.0.1.
Note that anycable gem v1.0.1 is also required.

**Comment by phlegx** [comment]
Hi @palkan! 

First of all, thanks for the fix!

I tried now the new version but for some reason I cannot connect to my sentinel. Getting this error: 

```
I 2020-07-09T20:15:31.775Z context=main Starting AnyCable 1.0.1-1551caf (pid: 1, open file limit: 1048576)
I 2020-07-09T20:15:31.775Z context=main Handle WebSocket connections at http://localhost:8080/cable
I 2020-07-09T20:15:31.775Z context=main Handle health connections at http://localhost:8080/health
I 2020-07-09T20:15:31.776Z context=metrics Serve metrics at http://localhost:8080/metrics
I 2020-07-09T20:15:31.776Z context=rpc RPC controller initialized: core-rpc.core.svc.cluster.local:50051 (concurrency: 28, proto_versions: v0,v1)
W 2020-07-09T20:15:31.777Z context=pubsub Failed to get master address from sentinel.
W 2020-07-09T20:15:31.777Z context=pubsub Failed to discover sentinels
E 2020-07-09T20:15:31.777Z context=main !!! Subscriber failed !!!
redigo: no sentinels available; last error: dial tcp: lookup redis on 10.43.0.10:53: no such host
```

Using this config where `redis-master` is the `mymaster` Sentinel name. I tried the config below with and without password disabling in bitnami redis helm chart:

``
`env {
  name = "ANYCABLE_REDIS_SENTINELS"
  value = "redis://:${var.redis_password}@redis-master:26379"
}
```

Any ideas what might be wrong? The IP/Port above looks suspicious.

**Comment by palkan** [comment]
> value = "redis://:${var.redis_password}@redis-master:26379"

It should be `"${var.redis_password}@redis-master:26379"`, w/o `redis://`. Not sure that's the reason though but let's try.

**Comment by phlegx** [comment]
Hi @palkan!

Thank you. I just tried your suggestion, but then I get this error:

```I 2020-07-10T08:26:34.843Z context=main Starting AnyCable 1.0.1-1551caf (pid: 1, open file limit: 1048576)
I 2020-07-10T08:26:34.843Z context=main Handle WebSocket connections at http://localhost:8080/cable
I 2020-07-10T08:26:34.843Z context=main Handle health connections at http://localhost:8080/health
W 2020-07-10T08:26:34.843Z context=pubsub Failed to get master address from sentinel.
E 2020-07-10T08:26:34.843Z context=main !!! Subscriber failed !!!
redigo: no sentinels available; last error: dial tcp: address :<password>:redis-master:26379: too many colons in address
```

**Comment by palkan** [comment]
Could you please turn debug mode on (`ANYCABLE_DEBUG=1`) and share the logs?

**Comment by phlegx** [comment]
@palkan sorry I just re-checked again this error was my mistake. I had a copy paste error and indeed there was a colon problem. I fixed it and now my string is same as yours:

```":${var.redis_password}@redis-master:26379"```

With that and ANYCABLE_DEBUG enabled I get:

```D 2020-07-10T08:41:37.099Z context=main 🔧 🔧 🔧 Debug mode is on 🔧 🔧 🔧
I 2020-07-10T08:41:37.099Z context=main Starting AnyCable 1.0.1-1551caf (pid: 1, open file limit: 1048576)
D 2020-07-10T08:41:37.099Z context=disconnector Calls rate: 10ms
I 2020-07-10T08:41:37.099Z context=main Handle WebSocket connections at http://localhost:8080/cable
I 2020-07-10T08:41:37.099Z context=main Handle health connections at http://localhost:8080/health
D 2020-07-10T08:41:37.099Z context=http Starting WebSocket server at http://localhost:8080
I 2020-07-10T08:41:37.099Z context=metrics Serve metrics at http://localhost:8080/metrics
D 2020-07-10T08:41:37.099Z context=http Metrics server is mounted at http://localhost:8080
D 2020-07-10T08:41:37.099Z context=pubsub Redis sentinel enabled
D 2020-07-10T08:41:37.099Z context=pubsub Redis sentinel parameters:  sentinels: :XXXXXXXXXXXXX@redis-master:26379,  masterName: localhost
I 2020-07-10T08:41:37.099Z context=rpc RPC controller initialized: core-rpc.core.svc.cluster.local:50051 (concurrency: 28, proto_versions: v0,v1)
D 2020-07-10T08:41:37.100Z context=pubsub Failed to connect to sentinel :XXXXXXXXXXXXX@redis-master:26379
D 2020-07-10T08:41:37.100Z context=pubsub Failed to connect to sentinel :XXXXXXXXXXXXX@redis-master:26379
W 2020-07-10T08:41:37.100Z context=pubsub Failed to discover sentinels
W 2020-07-10T08:41:37.100Z context=pubsub Failed to get master address from sentinel.
E 2020-07-10T08:41:37.100Z context=main !!! Subscriber failed !!!
redigo: no sentinels available; last error: dial tcp: lookup redis-master on 10.43.0.10:53: no such host
```

**Comment by Envek** [comment]
> `lookup redis-master on 10.43.0.10:53: no such host`

It looks like you have problem with name resolution (port 53 is usually used by DNS servers)

**Comment by phlegx** [comment]
I think the issue might be that `redis-master` is the sentinel `mymaster`. I'm not even sure if that master name is a valid DNS, obviously not.

**Comment by Envek** [comment]
No, it should not be valid hostname. It just a name under which it is known by Sentinels.
```
ANYCABLE_REDIS_URL=redis://:password@mymaster:6379/0
ANYCABLE_REDIS_SENTINELS=:password@anycable-redis-headless:26379
```
In this example `mymaster` is not a valid host. Only `anycable-redis-headless` should be name resolvable to Sentinels hosts.

Redis client connects to Sentinel at `anycable-redis-headless` port `26379` and asks “Where is `mymaster`?”, sentinel gives back address of actual Redis master instance.

**Comment by phlegx** [comment]
Thanks so much @Envek your example/suggestion now works for me as well! :-)

**Comment by phlegx** [comment]
@Envek 

> In this example `mymaster` is not a valid host. Only `anycable-redis-headless` should be name resolvable to Sentinels hosts.

One more general question: Can or even should we use the single kubernetes `headless` instance here, or is it better to pass all three - more more - instance DNS?

**Comment by Envek** [comment]
> Can or even should we use the single kubernetes headless instance here,

Yes it is assumed that Kubernetes service should be used to connect to Sentinels. Service will connect client app with random available sentinel.

While theoretically it is better to specify all sentinels in client app's configuration (so client library will try to access all three before reporting error), in practice it is cumbersome as it requires app reconfiguration every time you want to scale sentinels up or down (and requires you to use StatefulSets for them to have stable hostnames–[Bitnami's chart](https://github.com/bitnami/charts/tree/master/bitnami/redis) does that, but we think that it is a bit awkward and prefer [Redis Operator](https://github.com/spotahome/redis-operator) that uses Deployments). And because client library will connect to only one of sentinels anyway, IMO it is probably even better to have them spread between all sentinel instances by k8s service than have them all sitting on first sentinel from configuration list.

See [Redis service discovery via Sentinel](https://redis.io/topics/sentinel-clients#redis-service-discovery-via-sentinel) section in “Redis Sentinel clients guidelines” for details.

If you have any other Kubernetes, please feel free to ask them in [anycable-helm](https://github.com/anycable/anycable-helm/) repository issues.
