### ISSUE TITLE
Nonexistent channel cached?

### ISSUE THREAD

**Issue by prwhitehead** [anycable/anycable-go#121]
### Tell us about your environment

**AnyCable-Go version:**

1.0.1 (Latest)

**AnyCable gem version:**

anycable (1.0.1)
anycable-rails (1.0.1)

### What did you do?

I added a test channel called `WelcomeChannel`, which I then deleted, however my AnyCable container errors because it thinks the subscription still exists.

I have grep'd the directory and there is no mention of  `WelcomeChannel` in the project.

### What did you expect to happen?

That the AnyCable container does not register the `WelcomeChannel` subscription.

### What actually happened?

AnyCable tries to register a nonexisting subscription with the following debug logs: 

    websocket_1  | D 2020-09-12T15:08:33.675Z context=node sid=tGCdlxm4RONI54dBEGf_O Incoming message: &{subscribe {"channel":"WelcomeChannel"} }
    anycable_1   | deadline is 1969-12-31 23:59:59 +0000; (now=2020-09-12 15:08:33 +0000)
    anycable_1   | schedule another job
    anycable_1   | RPC Command: <AnyCable::CommandMessage: command: "subscribe", identifier: "{\"channel\":\"WelcomeChannel\"}", connection_identifiers: "{}", data: "", env: <AnyCable::Env: url: "http://localhost:8080/cable", headers: {"REMOTE_ADDR"=>"192.168.96.1", "cookie"=>"_session=5560f844aeb02d60c18bfcb9a3b1be144b72dd0142700ea9cbf227c77f76ae61; _app_session=p4vq1%2BdWsaVK6RAP6RpTvlCXCnPxhyNHhYVooSYJ11oYYS0ti1hD5if0vAUcfBzPEU11u6VmLnP69uBVHdB4G4FY7bqPiDVQIXZk7CPCn4Oa6rLIFw5rGRJvRrhhNYWdj%2Fo12cKFI5L8OnjBdhi8qRqRykWOYV0PGaL%2BGUK99qfhM3wqO%2F4cw7zj1GpvhVmjPGMXWV51yt7j0vt4m0CrzjSdrPk197d5CvSNSlsAt4%2BoloaqtBFRzgrMs4XLkFP1Un5ZKi2Tz0qwa6BwHeADEjlGdn8%3D--rY0mzdatN7slSoIY--v0zZF%2F51XKhch9nn7If0YA%3D%3D; _session_id=ef360634ad74850ed73298c0418af7fe"}, cstate: {"__ltags__"=>"[]"}, istate: {}>>
    anycable_1   | Subscription class not found: "WelcomeChannel"
    anycable_1   | Channel not found: WelcomeChannel:
    anycable_1   | /usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/refinements/subscriptions.rb:12:in `fetch'
    anycable_1   | /usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/actioncable/connection.rb:96:in `handle_channel_command'
    anycable_1   | /usr/local/bundle/gems/anycable-1.0.1/lib/anycable/rpc_handler.rb:79:in `command'
    anycable_1   | /usr/local/bundle/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:60:in `call'
    anycable_1   | /usr/local/bundle/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:60:in `block in handle_request_response'
    anycable_1   | /usr/local/bundle/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:178:in `block (2 levels) in intercept!'
    anycable_1   | /usr/local/bundle/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:178:in `block (2 levels) in intercept!'
    anycable_1   | /usr/local/bundle/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:181:in `block in intercept!'
    anycable_1   | /usr/local/bundle/gems/anycable-1.0.1/lib/anycable/middleware.rb:14:in `block in request_response'
    anycable_1   | /usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/middlewares/log_tagging.rb:16:in `block in call'
    anycable_1   | /usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:80:in `block in tagged'
    anycable_1   | /usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:28:in `tagged'
    anycable_1   | /usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:80:in `tagged'
    anycable_1   | /usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/middlewares/log_tagging.rb:16:in `call'
    anycable_1   | /usr/local/bundle/gems/anycable-1.0.1/lib/anycable/middleware.rb:13:in `request_response'
    anycable_1   | /usr/local/bundle/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:175:in `intercept!'
    anycable_1   | /usr/local/bundle/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:177:in `block in intercept!'
    anycable_1   | /usr/local/bundle/gems/anycable-1.0.1/lib/anycable/middleware.rb:14:in `block in request_response'
    anycable_1   | /usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/middlewares/executor.rb:16:in `block in call'
    anycable_1   | /usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
    websocket_1  | D 2020-09-12T15:08:33.686Z context=rpc Command response: error_msg:"Channel not found: WelcomeChannel"
    websocket_1  | E 2020-09-12T15:08:33.687Z context=node sid=tGCdlxm4RONI54dBEGf_O Subscribe error: Application error: Channel not found: WelcomeChannel
    websocket_1  | W 2020-09-12T15:08:33.687Z context=node sid=tGCdlxm4RONI54dBEGf_O Failed to handle incoming message '{"command":"subscribe","identifier":"{\"channel\":\"WelcomeChannel\"}"}' with error: Application error: Channel not found: WelcomeChannel

I thought it might have a record inside of `Redis`, however I tested this with a new `Redis` container without a shared volume and the issue continues. I am also seeing this error when running ANOTHER project that uses a similar setup, but should be distinct. 

When using the `async` adapter, the start up log is: 

    rails_1      | Started GET "/cable" for 192.168.96.1 at 2020-09-12 15:26:27 +0000
    rails_1      | Cannot render console from 192.168.96.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
    rails_1      | Started GET "/cable/" [WebSocket] for 192.168.96.1 at 2020-09-12 15:26:27 +0000
    rails_1      | Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
    rails_1      | StimulusReflex::Channel is transmitting the subscription confirmation
    rails_1      | StimulusReflex::Channel is streaming from StimulusReflex::Channel
    rails_1      | TodosChannel is transmitting the subscription confirmation
    rails_1      | TodosChannel is streaming from TodoChannel
    rails_1      | HelloChannel is transmitting the subscription confirmation
    rails_1      | HelloChannel is streaming from HelloChannel

The entire boot log is below incase that helps - I have a `HelloChannel`:

    anycable_1   | Starting AnyCable gRPC server (pid: 1, workers_num: 30)
    anycable_1   | AnyCable version: 1.0.1 (proto_version: v1)
    anycable_1   | gRPC version: 1.31.1
    anycable_1   | Serving Rails application from ./config/environment.rb
    anycable_1   | handling /anycable.RPC/Connect with #<Method: AnyCable::RPCHandler#connect>
    anycable_1   | handling /anycable.RPC/Command with #<Method: AnyCable::RPCHandler#command>
    anycable_1   | handling /anycable.RPC/Disconnect with #<Method: AnyCable::RPCHandler#disconnect>
    anycable_1   | handling /grpc.health.v1.Health/Check with #<Method: Grpc::Health::Checker#check>
    anycable_1   | handling /grpc.health.v1.Health/Watch with #<Method: Grpc::Health::Checker(Grpc::Health::V1::Health::Service)#watch>
    anycable_1   | Broadcasting Redis channel: __anycable__
    anycable_1   | RPC server is starting...
    anycable_1   | RPC server is listening on anycable:50051
    anycable_1   | deadline is 1969-12-31 23:59:59 +0000; (now=2020-09-12 15:45:08 +0000)
    anycable_1   | schedule another job
    anycable_1   | RPC Connect: <AnyCable::ConnectionRequest: env: <AnyCable::Env: url: "http://localhost:8080/cable", headers: {"REMOTE_ADDR"=>"192.168.96.1", "cookie"=>"_session=5560f844aeb02d60c18bfcb9a3b1be144b72dd0142700ea9cbf227c77f76ae61; _app_session=p4vq1%2BdWsaVK6RAP6RpTvlCXCnPxhyNHhYVooSYJ11oYYS0ti1hD5if0vAUcfBzPEU11u6VmLnP69uBVHdB4G4FY7bqPiDVQIXZk7CPCn4Oa6rLIFw5rGRJvRrhhNYWdj%2Fo12cKFI5L8OnjBdhi8qRqRykWOYV0PGaL%2BGUK99qfhM3wqO%2F4cw7zj1GpvhVmjPGMXWV51yt7j0vt4m0CrzjSdrPk197d5CvSNSlsAt4%2BoloaqtBFRzgrMs4XLkFP1Un5ZKi2Tz0qwa6BwHeADEjlGdn8%3D--rY0mzdatN7slSoIY--v0zZF%2F51XKhch9nn7If0YA%3D%3D; _session_id=4b2b3ef9e8cb34600e781bf1042dbeff"}, cstate: {}, istate: {}>>
    anycable_1   | Started "/cable" [AnyCable] for 192.168.96.1 at 2020-09-12 15:45:08 +0000
    websocket_1  | D 2020-09-12T15:45:08.320Z context=rpc Authenticate response: status:SUCCESS identifiers:"{}" transmissions:"{\"type\":\"welcome\"}" env:<cstate:<key:"__ltags__" value:"[]" > >
    websocket_1  | D 2020-09-12T15:45:08.321Z context=hub sid=QRzmj8P2Z1pMgGV3YgEho Registered with identifiers: {}
    websocket_1  | D 2020-09-12T15:45:08.321Z context=node sid=QRzmj8P2Z1pMgGV3YgEho websocket session established
    websocket_1  | D 2020-09-12T15:45:08.323Z context=node sid=QRzmj8P2Z1pMgGV3YgEho Incoming message: &{subscribe {"channel":"HelloChannel"} }
    anycable_1   | deadline is 1969-12-31 23:59:59 +0000; (now=2020-09-12 15:45:08 +0000)
    anycable_1   | schedule another job
    anycable_1   | RPC Command: <AnyCable::CommandMessage: command: "subscribe", identifier: "{\"channel\":\"HelloChannel\"}", connection_identifiers: "{}", data: "", env: <AnyCable::Env: url: "http://localhost:8080/cable", headers: {"REMOTE_ADDR"=>"192.168.96.1", "cookie"=>"_session=5560f844aeb02d60c18bfcb9a3b1be144b72dd0142700ea9cbf227c77f76ae61; _app_session=p4vq1%2BdWsaVK6RAP6RpTvlCXCnPxhyNHhYVooSYJ11oYYS0ti1hD5if0vAUcfBzPEU11u6VmLnP69uBVHdB4G4FY7bqPiDVQIXZk7CPCn4Oa6rLIFw5rGRJvRrhhNYWdj%2Fo12cKFI5L8OnjBdhi8qRqRykWOYV0PGaL%2BGUK99qfhM3wqO%2F4cw7zj1GpvhVmjPGMXWV51yt7j0vt4m0CrzjSdrPk197d5CvSNSlsAt4%2BoloaqtBFRzgrMs4XLkFP1Un5ZKi2Tz0qwa6BwHeADEjlGdn8%3D--rY0mzdatN7slSoIY--v0zZF%2F51XKhch9nn7If0YA%3D%3D; _session_id=4b2b3ef9e8cb34600e781bf1042dbeff"}, cstate: {"__ltags__"=>"[]"}, istate: {}>>
    anycable_1   | HelloChannel is transmitting the subscription confirmation
    websocket_1  | D 2020-09-12T15:45:08.330Z context=rpc Command response: status:SUCCESS streams:"HelloChannel" transmissions:"{\"identifier\":\"{\\\"channel\\\":\\\"HelloChannel\\\"}\",\"type\":\"confirm_subscription\"}" env:<>
    websocket_1  | D 2020-09-12T15:45:08.330Z context=node sid=QRzmj8P2Z1pMgGV3YgEho Subscribed to channel: {"channel":"HelloChannel"}
    websocket_1  | D 2020-09-12T15:45:08.330Z context=node sid=QRzmj8P2Z1pMgGV3YgEho Incoming message: &{subscribe {"channel":"WelcomeChannel"} }
    websocket_1  | D 2020-09-12T15:45:08.331Z channel={"channel":"HelloChannel"} context=hub sid=QRzmj8P2Z1pMgGV3YgEho stream=HelloChannel Subscribed
    anycable_1   | deadline is 1969-12-31 23:59:59 +0000; (now=2020-09-12 15:45:08 +0000)
    anycable_1   | schedule another job
    anycable_1   | RPC Command: <AnyCable::CommandMessage: command: "subscribe", identifier: "{\"channel\":\"WelcomeChannel\"}", connection_identifiers: "{}", data: "", env: <AnyCable::Env: url: "http://localhost:8080/cable", headers: {"REMOTE_ADDR"=>"192.168.96.1", "cookie"=>"_session=5560f844aeb02d60c18bfcb9a3b1be144b72dd0142700ea9cbf227c77f76ae61; _app_session=p4vq1%2BdWsaVK6RAP6RpTvlCXCnPxhyNHhYVooSYJ11oYYS0ti1hD5if0vAUcfBzPEU11u6VmLnP69uBVHdB4G4FY7bqPiDVQIXZk7CPCn4Oa6rLIFw5rGRJvRrhhNYWdj%2Fo12cKFI5L8OnjBdhi8qRqRykWOYV0PGaL%2BGUK99qfhM3wqO%2F4cw7zj1GpvhVmjPGMXWV51yt7j0vt4m0CrzjSdrPk197d5CvSNSlsAt4%2BoloaqtBFRzgrMs4XLkFP1Un5ZKi2Tz0qwa6BwHeADEjlGdn8%3D--rY0mzdatN7slSoIY--v0zZF%2F51XKhch9nn7If0YA%3D%3D; _session_id=4b2b3ef9e8cb34600e781bf1042dbeff"}, cstate: {"__ltags__"=>"[]"}, istate: {}>>
    anycable_1   | Subscription class not found: "WelcomeChannel"
    anycable_1   | Channel not found: WelcomeChannel:
    anycable_1   | /usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/refinements/subscriptions.rb:12:in `fetch'
    anycable_1   | /usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/actioncable/connection.rb:96:in `handle_channel_command'
    anycable_1   | /usr/local/bundle/gems/anycable-1.0.1/lib/anycable/rpc_handler.rb:79:in `command'
    anycable_1   | /usr/local/bundle/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:60:in `call'
    anycable_1   | /usr/local/bundle/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:60:in `block in handle_request_response'
    anycable_1   | /usr/local/bundle/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:178:in `block (2 levels) in intercept!'
    anycable_1   | /usr/local/bundle/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:178:in `block (2 levels) in intercept!'
    anycable_1   | /usr/local/bundle/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:181:in `block in intercept!'
    anycable_1   | /usr/local/bundle/gems/anycable-1.0.1/lib/anycable/middleware.rb:14:in `block in request_response'
    anycable_1   | /usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/middlewares/log_tagging.rb:16:in `block in call'
    anycable_1   | /usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:80:in `block in tagged'
    anycable_1   | /usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:28:in `tagged'
    anycable_1   | /usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:80:in `tagged'
    anycable_1   | /usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/middlewares/log_tagging.rb:16:in `call'
    anycable_1   | /usr/local/bundle/gems/anycable-1.0.1/lib/anycable/middleware.rb:13:in `request_response'
    anycable_1   | /usr/local/bundle/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:175:in `intercept!'
    anycable_1   | /usr/local/bundle/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:177:in `block in intercept!'
    anycable_1   | /usr/local/bundle/gems/anycable-1.0.1/lib/anycable/middleware.rb:14:in `block in request_response'
    anycable_1   | /usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/middlewares/executor.rb:16:in `block in call'
    anycable_1   | /usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
    websocket_1  | D 2020-09-12T15:45:08.337Z context=rpc Command response: error_msg:"Channel not found: WelcomeChannel"
    websocket_1  | E 2020-09-12T15:45:08.337Z context=node sid=QRzmj8P2Z1pMgGV3YgEho Subscribe error: Application error: Channel not found: WelcomeChannel
    websocket_1  | W 2020-09-12T15:45:08.337Z context=node sid=QRzmj8P2Z1pMgGV3YgEho Failed to handle incoming message '{"command":"subscribe","identifier":"{\"channel\":\"WelcomeChannel\"}"}' with error: Application error: Channel not found: WelcomeChannel
    anycable_1   | deadline is 1969-12-31 23:59:59 +0000; (now=2020-09-12 15:45:18 +0000)
    anycable_1   | schedule another job
    anycable_1   | RPC Connect: <AnyCable::ConnectionRequest: env: <AnyCable::Env: url: "http://localhost:8080/cable", headers: {"REMOTE_ADDR"=>"192.168.96.1", "cookie"=>"_session=5560f844aeb02d60c18bfcb9a3b1be144b72dd0142700ea9cbf227c77f76ae61; _app_session=p4vq1%2BdWsaVK6RAP6RpTvlCXCnPxhyNHhYVooSYJ11oYYS0ti1hD5if0vAUcfBzPEU11u6VmLnP69uBVHdB4G4FY7bqPiDVQIXZk7CPCn4Oa6rLIFw5rGRJvRrhhNYWdj%2Fo12cKFI5L8OnjBdhi8qRqRykWOYV0PGaL%2BGUK99qfhM3wqO%2F4cw7zj1GpvhVmjPGMXWV51yt7j0vt4m0CrzjSdrPk197d5CvSNSlsAt4%2BoloaqtBFRzgrMs4XLkFP1Un5ZKi2Tz0qwa6BwHeADEjlGdn8%3D--rY0mzdatN7slSoIY--v0zZF%2F51XKhch9nn7If0YA%3D%3D; _session_id=a9156e6b56296165586955fa54b755d4"}, cstate: {}, istate: {}>>
    anycable_1   | Started "/cable" [AnyCable] for 192.168.96.1 at 2020-09-12 15:45:18 +0000
    websocket_1  | D 2020-09-12T15:45:18.719Z context=rpc Authenticate response: status:SUCCESS identifiers:"{}" transmissions:"{\"type\":\"welcome\"}" env:<cstate:<key:"__ltags__" value:"[]" > >
    websocket_1  | D 2020-09-12T15:45:18.719Z context=node sid=eVdv9jRYEzjnUKVZU0Qf3 websocket session established
    websocket_1  | D 2020-09-12T15:45:18.719Z context=hub sid=eVdv9jRYEzjnUKVZU0Qf3 Registered with identifiers: {}
    websocket_1  | D 2020-09-12T15:45:18.730Z context=node sid=eVdv9jRYEzjnUKVZU0Qf3 Incoming message: &{subscribe {"channel":"HelloChannel"} }
    anycable_1   | deadline is 1969-12-31 23:59:59 +0000; (now=2020-09-12 15:45:18 +0000)
    anycable_1   | schedule another job
    anycable_1   | RPC Command: <AnyCable::CommandMessage: command: "subscribe", identifier: "{\"channel\":\"HelloChannel\"}", connection_identifiers: "{}", data: "", env: <AnyCable::Env: url: "http://localhost:8080/cable", headers: {"REMOTE_ADDR"=>"192.168.96.1", "cookie"=>"_session=5560f844aeb02d60c18bfcb9a3b1be144b72dd0142700ea9cbf227c77f76ae61; _app_session=p4vq1%2BdWsaVK6RAP6RpTvlCXCnPxhyNHhYVooSYJ11oYYS0ti1hD5if0vAUcfBzPEU11u6VmLnP69uBVHdB4G4FY7bqPiDVQIXZk7CPCn4Oa6rLIFw5rGRJvRrhhNYWdj%2Fo12cKFI5L8OnjBdhi8qRqRykWOYV0PGaL%2BGUK99qfhM3wqO%2F4cw7zj1GpvhVmjPGMXWV51yt7j0vt4m0CrzjSdrPk197d5CvSNSlsAt4%2BoloaqtBFRzgrMs4XLkFP1Un5ZKi2Tz0qwa6BwHeADEjlGdn8%3D--rY0mzdatN7slSoIY--v0zZF%2F51XKhch9nn7If0YA%3D%3D; _session_id=a9156e6b56296165586955fa54b755d4"}, cstate: {"__ltags__"=>"[]"}, istate: {}>>
    anycable_1   | HelloChannel is transmitting the subscription confirmation
    websocket_1  | D 2020-09-12T15:45:18.735Z context=rpc Command response: status:SUCCESS streams:"HelloChannel" transmissions:"{\"identifier\":\"{\\\"channel\\\":\\\"HelloChannel\\\"}\",\"type\":\"confirm_subscription\"}" env:<>
    websocket_1  | D 2020-09-12T15:45:18.736Z context=node sid=eVdv9jRYEzjnUKVZU0Qf3 Subscribed to channel: {"channel":"HelloChannel"}
    websocket_1  | D 2020-09-12T15:45:18.736Z context=node sid=eVdv9jRYEzjnUKVZU0Qf3 Incoming message: &{subscribe {"channel":"TodosChannel"} }
    websocket_1  | D 2020-09-12T15:45:18.736Z channel={"channel":"HelloChannel"} context=hub sid=eVdv9jRYEzjnUKVZU0Qf3 stream=HelloChannel Subscribed

**Comment by palkan** [comment]
> The entire boot log

The log also includes a client actions:

```
D 2020-09-12T15:45:08.320Z context=rpc Authenticate response: status:SUCCESS identifiers:"{}" transmissions:"{\"type\":\"welcome\"}" env:<cstate:<key:"__ltags__" value:"[]" > >
websocket_1  | D 2020-09-12T15:45:08.321Z context=hub sid=QRzmj8P2Z1pMgGV3YgEho Registered with identifiers: {}
websocket_1  | D 2020-09-12T15:45:08.323Z context=node sid=QRzmj8P2Z1pMgGV3YgEho Incoming message: &{subscribe {"channel":"HelloChannel"} }
websocket_1  | D 2020-09-12T15:45:08.330Z context=node sid=QRzmj8P2Z1pMgGV3YgEho Incoming message: &{subscribe {"channel":"WelcomeChannel"} }
```

`Incoming message ...` logs are printed every time a client sends a message to a server. Hence, the WelcomeChannel subscription is attempted by some client (likely, a browser tab which hasn't been refreshed for a long time and, thus, having stale frontend code or trying to restore a broken connection with the old subscriptions).

**Comment by palkan** [comment]
Closed as stale.
