### ISSUE TITLE
Huge amount of incoming requests after deploy

### ISSUE THREAD

**Issue by Michaelvilleneuve** [anycable/anycable-go#123]
### Tell us about your environment

**AnyCable-Go version: 1.0**

**AnyCable gem version: 1.0.2**

### What did you do?

Deployed the app when **almost no one was connected to the APP**

### What did you expect to happen?

A reasonable number of unsubscribe / subscribes requests and CPU usage.
Doing the exact same deploy with ActionCable and the same number of connected people would not cause such high  spikes

### What actually happened?

After deploying anycable we notice a huge number of requests (up to 2400/sec despite something like 10people connected):

<img width="821" alt="image" src="https://user-images.githubusercontent.com/4990201/97771234-3cae2c00-1b3b-11eb-819e-d79d95e3d8f5.png">

Most of these requests were similar to the following : 

```
{"method":{},"path":{},"format":{},"params":null,"controller":"QuestionsChannel","action":"unsubscribe","status":200,"duration":0.04,"time":447107.640597108,"remote_ip":null,"subject":null,"version":null,"account_id":null}
```

CPU Usage during the deploy with almost no live connections :

<img width="611" alt="Screenshot 2020-10-31 at 05 31 44" src="https://user-images.githubusercontent.com/4990201/97771219-1d170380-1b3b-11eb-8c97-0c75a89e7010.png">

Is there something we're doing wrong ? Thank you very much

**Comment by palkan** [comment]
> up to 2400/sec despite something like 10people connected

Wow, that's huge.

Do you collect anycable-go [metrics](https://docs.anycable.io/#/v1/anycable-go/instrumentation?id=anycable-go-instrumentation)? It would be great to see RPC calls stats.

What do you see in a browser logs?

`unsubscribe` is called either directly (i.e., your via a client request) or during the `disconnect` phase (which is more likely). 

Do you rely on Action Cable built-in reconnection mechanism or use your own?

**Comment by Michaelvilleneuve** [comment]
Hello, thanks for your response. Browser logs look just fine, the retry strategy seems fine too. 
Yes we rely on Action Cable built-in reconnection mechanism. 😕
We do not collect those logs for now, I'll try to add them in the next few weeks.

**Comment by palkan** [comment]
Hey @Michaelvilleneuve! Any updates?

**Comment by palkan** [comment]
Closed as stale
