### ISSUE TITLE
Failed to handle incoming with error: Application error:

### ISSUE THREAD

**Issue by AlexWayfer** [anycable/anycable-go#138]
### Tell us about your environment

**AnyCable-Go version:** 1.1.1-7c02027

**AnyCable gem version:** v1.0.3

### What did you do?

Uses `reject` method inside `Channel`.

https://api.rubyonrails.org/classes/ActionCable/Channel/Base.html#class-ActionCable::Channel::Base-label-Rejecting+subscription+requests

### What did you expect to happen?

Rejection and no errors.

### What actually happened?

```  
 DEBUG 2021-06-22T16:14:43.002Z context=node sid=uSme40QlHlHt8nLtnmSnc Incoming message: &{subscribe {"channel":"UserSlotChannel"} }
 DEBUG 2021-06-22T16:14:43.006Z context=rpc sid=uSme40QlHlHt8nLtnmSnc Command response: status:FAILURE stop_streams:true transmissions:"{\"identifier\":\"{\\\"channel\\\":\\\"UserSlotChannel\\\"}\",\"type\":\"reject_subscription\"}" env:<> 
 ERROR 2021-06-22T16:14:43.006Z context=node sid=uSme40QlHlHt8nLtnmSnc Subscribe error: Application error: 
  WARN 2021-06-22T16:14:43.007Z context=node sid=uSme40QlHlHt8nLtnmSnc Failed to handle incoming message '{"command":"subscribe","identifier":"{\"channel\":\"UserSlotChannel\"}"}' with error: Application error: 
 DEBUG 2021-06-22T16:14:43.007Z channel={"channel":"UserSlotChannel"} context=hub sid=uSme40QlHlHt8nLtnmSnc Unsubscribed
```

`bundle exec anycable` outputs nothing.

**Comment by palkan** [comment]
Thanks for reporting.

Subscription rejection should be logged as error, definitely.

Fixed by https://github.com/anycable/anycable-go/commit/9483f39a49035d6b7b9b8d877d1537b796f2278b
