### ISSUE TITLE
GRPC max message size

### ISSUE THREAD

**Issue by bgaj** [anycable/anycable-go#143]
### Tell us about your environment

**AnyCable-Go version: 1.1.3-35cdedf**

**AnyCable gem version: 1.0.3**

### What did you do?

I try to receive message large message (over 5MB). I set ANYCABLE_MAX_MESSAGE_SIZE to 10M.

### What did you expect to happen?

Receive a message

### What actually happened?
I get error:
`error: rpc error: code = desc = Received message larger than max (6994086 vs. 4194304)`

**Comment by palkan** [comment]
Added `rpc_max_call_recv_size` and `rpc_max_call_send_size` in v1.1.4.

**Comment by bgaj** [comment]
@palkan There is still problem with increasing the limit above 4194304. In opossite direcetion everything works fine

**Comment by bgaj** [comment]
@palkan Did you have time to check it again?

**Comment by palkan** [comment]
Hey @bgaj,

Yeah, I've been triaging it today.

It looks like we also need to adjust server settings.
Here is what I tried: `ANYCABLE_RPC_SERVER_ARGS__MAX_RECEIVE_MESSAGE_LENGTH=10000000 bundle exec anycable`. GRPC errors disappeared (but my local client failed to read that amount of data). Haven't had a chance to test with a real browser.
