### ISSUE TITLE
JWT auth enhancements

### ISSUE THREAD

**Issue by str1nker** [anycable/anycable-go#146]
### Tell us about your environment

**AnyCable-Go version:** 1.2

**AnyCable gem version:** 1.2.2

Trying to use anycable-go server JWT auth brings some difficulties:
1) Hard coded connection identifier JWT claim ( `ext` ) . Sometimes it's hard to edit JWT as it could be from another auth service like `Keycloak`.
2) Hard coded connection identifier type (`string`). Same issue as above.
3) Seems like Go server doesn't send RPC connection request when JWT auth is activated  so `ApplicationCable::Connection#connect` method is never called. It was a good place to identify application user...

I hope something above makes sense. Thank you a lot for an awesome product!

**Comment by palkan** [comment]
Hey!

Let's start with the latter one:

> Seems like Go server doesn't send RPC connection request when JWT auth is activated so

Yep, that's the point of AnyCable JWT Identification—_pre-identify_ a user and avoid calling RPC. That also explains the format of the token contents (1 and 2).

If you want to use your custom JWT authentication, you should just let `anycable-go` to perform an RPC call and not to anything else. For that, you need to disable this feature.
