### ISSUE TITLE
readme shows invalid "go get" command

### ISSUE THREAD

**Issue by inspire22** [anycable/anycable-go#149]
I get this error:
root@blah~# go get -u -f github.com/anycable/anycable-go/cmd/anycable-go
go: -f flag is a no-op when using modules
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.

**Comment by palkan** [comment]
Thanks! Fixed.
