### ISSUE TITLE
Hide `Disconnect error: grpc connection is not ready` message

### ISSUE THREAD

**Issue by SebastianSzturo** [anycable/anycable-go#170]
Is it possible to hide the `Disconnect error: grpc connection is not ready` error when using anycable-go without an grpc client (e.g. for Hotwire only).

**Comment by palkan** [comment]
Yes, you need to disable _disconnector_ via `--disable_disconnect` or `ANYCABLE_DISABLE_DISCONNECT=1` (see [docs](https://docs.anycable.io/anycable-go/signed_streams))
