### ISSUE TITLE
Latest docker image missing GLIBC_2.29

### ISSUE THREAD

**Issue by marcosyu** [anycable/anycable-go#179]
### Tell us about your environment

**AnyCable-Go version: latest**

**AnyCable gem version: 1.3**

### What did you do?
Startup anycable go with the flags host, port, debug, rpc_host
### What did you expect to happen?
For anycable-go to start
### What actually happened?
It runs into an error 

```
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by anycable-go)
```

**Comment by palkan** [comment]
Hey Marcos,


Could you please provide a bit more details? OS version, Docker image ID/checksum (or the full output of `docker inspect ...`)?

**Comment by Envek** [comment]
I can confirm that it happens on `1.4.0-mrb` image (also aliased as `latest` now):

```
$ docker run --ulimit nofile=65536:65536 -p 8080:8080 -e "REDIS_URL=redis://redis:6379/0" -e "ANYCABLE_RPC_HOST=rpc:50051" -e "ANYCABLE_HOST=0.0.0.0" anycable/anycable-go:1.4.0-mrb
/usr/local/bin/anycable-go: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/bin/anycable-go)
```

This docker image [is based on Debian 10 (buster)](https://github.com/anycable/anycable-go/blob/45526a575621c2c9197e63e656f6f4733fafab20/.docker/Dockerfile.mrb-linux-amd64#L1) which [has GLibC 2.28](https://packages.debian.org/buster/amd64/libc6/download). But anycable-go binary requires at least 2.29 (Go upgrade maybe?)

---

Debian 10 (buster) is obsoleted (now under LTS support till 2024), so probably it is time to migrate to newer Debian 11 (bullseye) [with GlibC 2.31](https://packages.debian.org/bullseye/amd64/libc6/download) or Debian 12 (bookworm) with [GLibC 2.36](https://packages.debian.org/bookworm/amd64/libc6/download).

**Comment by palkan** [comment]
Thanks, @Envek!

> it happens on 1.4.0-mrb image (also aliased as latest now):

Oh, that's bad; it should be `latest-mrb`.

> Go upgrade maybe?

Yep.

**Comment by palkan** [comment]
@marcosyu For now, using `anycable/anycable-go:1.4` should fix the issue.

**Comment by Envek** [comment]
Right now both `latest` and `latest-mrb` works, seems to be correct (without and with mruby respectively).

Use `docker pull` (or `--pull=always` option for `docker run`) to update image locally.

**Comment by palkan** [comment]
Ok, re-published the images; should work now.
