### ISSUE TITLE
No documentation on Docker usage

### ISSUE THREAD

**Issue by devinturner** [anycable/anycable-go#18]
It would be nice if there were environment variables and basic usage available in Docker Hub or in the README.

<img width="872" alt="screen shot 2017-10-24 at 5 15 13 pm" src="https://user-images.githubusercontent.com/4925561/31968386-f25fc116-b8de-11e7-9360-9ff355ad4180.png">

**Comment by palkan** [comment]
Done https://hub.docker.com/r/anycable/anycable-go/

**Comment by devinturner** [comment]
Awesome!
