### ISSUE TITLE
Failed to install by source

### ISSUE THREAD

**Issue by ricardopacheco** [anycable/anycable-go#191]
### Tell us about your environment

**AnyCable-Go version**: 1.4.4

**AnyCable gem version**: 1.4.2

**go version**: 1.21.1

### What did you do?

Run command `go install github.com/anycable/anycable-go/cmd/anycable-go@latest`

### What did you expect to happen?

Anycable install sucessfully

### What actually happened?

```
❯ go install github.com/anycable/anycable-go/cmd/anycable-go@latest
go: github.com/anycable/anycable-go/cmd/anycable-go@latest (in github.com/anycable/anycable-go@v1.4.4):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

**Comment by palkan** [comment]
Fixed by https://github.com/anycable/anycable-go/commit/21d4dbe764d0502dc74b7f8c6a7da5c58dc0aa31.

Will take an effect after the next release is published. Currently, you can use the following command to install from source:

```
go install github.com/anycable/anycable-go/cmd/anycable-go@v1.4.4.1
```

**Comment by RISCfuture** [comment]
a `replace` directive was re-added with 6249e6534ac5b186b1745f9670e1a700f73b5778, fyi
