### ISSUE TITLE
Posthog

### ISSUE THREAD

**Issue by iHiD** [anycable/anycable-go#192]
Hello. I've noticed that when I run `anycable-go` locally with my internet disabled I get the following message:
```
posthog 2023/09/28 13:23:55 ERROR: sending request - Post "https://app.posthog.com/batch/": dial tcp: lookup app.posthog.com: no such host
```
Screenshot:
<img width="1283" alt="Screenshot 2023-09-28 at 13 24 08" src="https://github.com/anycable/anycable-go/assets/286476/8d4fc44a-0820-4f5f-a626-da9a80cb3844">

Do you have any idea what posthog is or why anycable is sending it data from my machine?

Thanks.

**Comment by palkan** [comment]
> Do you have any idea what posthog is or why anycable is sending it data from my machine?

Yes, this is our telemetry collection: https://docs.anycable.io/anycable-go/telemetry (see the second line in the logs from your screenshot).

The real question is why it keeps retrying (and so often) and prints errors into stdout.
