### ISSUE TITLE
Cookie auth broken in v1.5.5

### ISSUE THREAD

**Issue by iuri-gg** [anycable/anycable-go#210]
### Tell us about your environment

**AnyCable-Go version:** v1.5.5

**AnyCable gem version:**
* anycable (1.5.1)
* anycable-core (1.5.1)
* anycable-rails (1.5.4)
* anycable-rails-core (1.5.4)

### What did you do?
1. Upgraded anycable-go to v1.5.5.
2. start the server using `anycable-go --port=8080 --debug`

### What did you expect to happen?
Client to continue working after `anycable-go` version upgrade

### What actually happened?
Got client auth errors. 

#### Debugging
1. Used `--print-config` to see difference of config between two versions. 
2. Found the diff: `proxy_headers = [""]` vs `proxy_headers = ["cookie"]`. 
3. started using `--headers cookie` flag and auth error got fixed.

**Comment by palkan** [comment]
Thanks for the report. Fixed in 1.5.6.
