### ISSUE TITLE
Mass broadcast

### ISSUE THREAD

**Issue by alekseyl** [anycable/anycable-go#22]
Может сделать возможность массовой рассылки на все открытые соединения? 

Может быть удобно при деплое, дать всем знать, что сейчас планово оборвется связь и нужно без паники переконнектиться и быть готовым обновиться.

В целом изменение в коде будет небольшим.

**Comment by palkan** [comment]
> Может быть удобно при деплое, дать всем знать, что сейчас планово оборвется связь и нужно без паники переконнектиться и быть готовым обновиться.

Да, это хороший момент.
Это уже выходит за рамки ActionCable (но это и есть финальная цель проекта).

Мысль такая: сделать зарезервированное имя стрима и обрабатывать его специальным образом, то есть:

```ruby
# в ActionCable
ActionCable.server.broadcast "anycable:internal:all", msg
```

```go
// в subscriber.go
if msg.Stream == "anycable:internal:all" {
  # у нас уже есть канал для отправки данных всем
  h.broadcast <- msg.Data
}
```

**Comment by alekseyl** [comment]
В настоящий момент кстати, это можно эмулировать, на уровне стримов. Сделать отдельный канал для этого и сделать специальный стрим "anycable:internal:all" и на него подписать все соединения. И там слать служебную инфу, если есть потребность.

**Comment by palkan** [comment]
Да, можно и так. Но стрим _живёт_ в рамках какого-то канала, значит нужно еще и канал добавить.

С другой стороны, вся логика тогда будет в приложении, а не скрыта где-то внутри anycable.

**Comment by palkan** [comment]
Пока остановимся на варианте с каналом.
Для массового броадкаста нужно также обновлять клиентскую часть (и, вероятно, протокол). В рамках 1.0 и совместимости с Action Cable это невозможно. Будем планировать в рамках 2.0 (унёс себе в беклог).
