### ISSUE TITLE
Broadcast string appears as null

### ISSUE THREAD

**Issue by jnstq** [anycable/anycable-go#23]
Thanks for an awesome project! I would love to try this in our production app. I think we can save a lot of heroku dynos as we have problem with memory and number of connections.

We are sending server rendered html or json returned by postgres directly with ActionCable, but it do look like this isn't working with AnyCable. 

```ruby
# Works
ActionCable.server.broadcast "class_section_189", { name: "Testing" }
```

```ruby
# Does not work
ActionCable.server.broadcast "class_section_189", "Testing"
```

**Versions**
Rails 5.1.4
Ruby 2.4.2
AnyCable websocket server v0.5.0.1

<img width="946" alt="screen shot 2017-12-19 at 17 15 53" src="https://user-images.githubusercontent.com/20176/34166905-7ce091e4-e4e0-11e7-9278-a926f31e28d2.png">

**Comment by palkan** [comment]
Fixed and released as 0.5.2

**Comment by jnstq** [comment]
Super, just installed and tested 👌🏼 Next up, heroku

**Comment by jnstq** [comment]
I've run in to another issue on replacing ActionCable with AnyCable.

I requests json directly from postgres, sending it as a string via broadcast.

To simulate it

```ruby
ActionCable.server.broadcast "class_section_273411", Oj.dump(name: "TEST")
```

On my received method in javascript

```javascript
  onServerClassSection: function (message) { // message = ""{\"name\":\"TEST\"}""
    if (this.isMounted()) {
      var data = JSON.parse(message); // data = "{"name":"TEST"}"
      this.loadClassSection(data);
    }
  },
```

**Comment by jnstq** [comment]
Sending rendered html from server

```ruby
ActionCable.server.broadcast "class_section_table_273411", "<table><tbody><tr><td>TEST</td></tr></tbody></table>"
```

```javascript
  onServerData: function (message) { // message = ""\u003ctable\u003e\u003ctbody\u003e\u003ctr\u003e\u003ctd\u003eTEST\u003c/td\u003e\u003c/tr\u003e\u003c/tbody\u003e\u003c/table\u003e""
    if (this.isMounted()) this.loadData(message);
  },

  // JSON.parse(message) would return the correct string "<table><tbody><tr><td>TEST</td></tr></tbody></table>"
```

**Comment by palkan** [comment]
Interesting, I didn't take into account this case.

I'll try to fix it today. Do you use precompiled version of `anycable-go` or built from source?

**Comment by jnstq** [comment]
Thanks! In development I'm install from source, and on heroku the buildpack

**Comment by palkan** [comment]
@jnstq Check out master version, please; should work now the same way as Action Cable does

**Comment by jnstq** [comment]
@palkan Locally it works exactly as ActionCable now. Can you publish a new version so I can try it on Heroku?

**Comment by palkan** [comment]
Yep, gimme 10 minutes

**Comment by palkan** [comment]
@jnstq Ready
