### ISSUE TITLE
ping + log

### ISSUE THREAD

**Issue by alekseyl** [anycable/anycable-go#24]
Надо иметь возможность отделить вывод пингов в лог от остальных броадкастов. Через параметры запуска или перенести пинги из DEBUG в INFO ( но это не бьется с текущим броадкастом, который логгирует все сообщения выводит в дебаг лог ).
  
Потому что логгирование, особенно живое в девелопменте, практически смысла не имеет, все погребается пингами в клочья.

я себе локально сделал broadcast_silent для дева, но это надо как-то вытащить на какой-то разумный управляемый уровень.

Я не умею в go поэтому PR не могу сделать адекватный.

**Comment by palkan** [comment]
В новой версии ping переписан, логов у него не будет.
https://github.com/anycable/anycable-go/releases/tag/v0.6.0-preview1
