### ISSUE TITLE
Redis subscription stops working

### ISSUE THREAD

**Issue by pokonski** [anycable/anycable-go#25]
Hey!

I noticed one issue with the server: after 10 hours of running the anycable-go it stopped receiving Redis messages with broadcasts.

I inspected logs using `-log` option and manually subscribed to the Redis channel via `redis-cli` and the messages are coming, but `anycable-go` does not seem to receive them.

My best guess is that it does not correctly reconnect after timeout/network issues.

Restarting the anycable-go fixes the issue, but temporarily until another issue where it stops receiving pubsub from Redis again.

Some artificial steps to reproduce:

1. Start WS subscription the usual way
2. Perform broadcasts to see that it works
3. Stop Redis server
4. Start Redis server
5. Anycable-Go never tries to connect again and further PUBSUB messages from Redis are lost and never arrive again

**Comment by palkan** [comment]
Thanks for the report! I'll take a look at this issue ASAP. Looks like a bad bug(

**Comment by pokonski** [comment]
@palkan thanks for the quick response! I tracked to a potential issue in redigo library anycable-go is using: https://github.com/garyburd/redigo/issues/295

**Comment by palkan** [comment]
@pokonski Fixed and released as 0.5.4

**Comment by pokonski** [comment]
That's fantastic! I'll give it a try :)
