### ISSUE TITLE
client message size as option?

### ISSUE THREAD

**Issue by rus-max** [anycable/anycable-go#30]
Hi, I'm using anycable-go 0.6.0-preview2. Client sends base64-encoded image to server and its disconnected. How to increase client message size limit?

I forked repo, comment this [line](https://github.com/anycable/anycable-go/blame/5e24c694cb5359794ef2046e4f47530b06f0e8a2/node/session.go#L155) and install from fork.

But nothing has changed. Thanks

**Comment by palkan** [comment]
Hi!

> Client sends base64-encoded image to server

What's the size of the resulted message?

> its disconnected

Do you see any errors in log? Have you tried to run the server with `--debug` option? What about RPC server logs?

**Comment by rus-max** [comment]
Size message: 872471

anycable.yml
```
production:
  rpc_host: "localhost:50051"
  log_grpc: true
  log_file: '/home/deploy/myapp/shared/log/anycable.log'
  debug: true # Shortcut to enable GRPC logging and debug level
  log_level: info
  redis_channel: "__anycable__"
  redis_sentinels: []
```
Procfile
```
web: bundle exec puma -C config/puma.rb
sidekiq: bundle exec sidekiq -C config/sidekiq.yml
rpc: bundle exec ./bin/anycable
anycable-go: bundle exec ./bin/anycable-go-0.6.1 --host=0.0.0.0 --port=3334  --path=/ws --debug
```
The log file doesn`t contain errors.
I see logs in production.log, but no logs is in anycable.log.

**Comment by palkan** [comment]
Thanks! I'll try to reproduce and find out what's going on here.

**Comment by WalkPhoneGo** [comment]
still have this problem
rails 5.2.2
ruby 2.5.3
anycabel-go anycable-go-v0.6.1-linux-amd64

when I send message size about 200k, the connection will close.

**Comment by WalkPhoneGo** [comment]
> still have this problem
> rails 5.2.2
> ruby 2.5.3
> anycabel-go anycable-go-v0.6.1-linux-amd64
> 
> when I send message size about 200k, the connection will close.

I just find the maxSize is 64K, so why set 64k not even bigger size?

**Comment by sponomarev** [comment]
It’s basically a way to limit memory consumption during workload. Otherwise, a malicious client can cause DoS easier. 

There is a plan to make this value configurable soon.

**Comment by palkan** [comment]
> There is a plan to make this value configurable soon.

Yep. I planned to add support for customising low-level options via `*.toml` configuration, but then we decided not to mess with file-based configs.

We'll add this options support via CLI/ENV.

@sponomarev Would you like to work on that 😉?)

**Comment by nixme** [comment]
Please take a look at #66 to address this.
