### ISSUE TITLE
Time for Notifier Disconnected

### ISSUE THREAD

**Issue by bpdarlyn** [anycable/anycable-go#31]
Do you know what is the time about notifier disconnection ?

**Comment by palkan** [comment]
Could you, please, explain more precisely? I'm not sure I got what you mean

**Comment by bpdarlyn** [comment]
Ok!  when the client socket is disconnected, the websocket server takes almost 10 minutes in disconnected and notifier to rails app in my case, this time for retry connection is configurable or for It take as disconnected  is configurable ?

**Comment by palkan** [comment]
Do you use version 0.6.0? If so, try to use master version, I've pushed a possible fix

**Comment by bpdarlyn** [comment]
ok thank !! I am gonna look this. :+1:
