### ISSUE TITLE
ERROR on installing from source

### ISSUE THREAD

**Issue by alekseyl** [anycable/anycable-go#32]
go get -u -f github.com/anycable/anycable-go/cmd/anycable-go

Delivers ERROR: 
package context: unrecognized import path "context" (import path does not begin with hostname)

**Comment by palkan** [comment]
What is your Go version?

**Comment by alekseyl** [comment]
go version go1.6.2 linux/amd64

**Comment by palkan** [comment]
Go 1.10+ is required for the latest version

**Comment by alekseyl** [comment]
The best way to install it from console in ubuntu would be...?

sudo curl -O https://storage.googleapis.com/golang/go1.10...
sudo tar -xvf go1.10...
sudo mv go /usr/local 

any chance to use apt-get?

**Comment by alekseyl** [comment]
ut if I use binary I don't need to install go lang am I right?

**Comment by palkan** [comment]
> if I use binary I don't need to install go lang am I right?

Yep, correct

> any chance to use apt-get?

Frankly speaking, have no idea on how to install go on Ubuntu

**Comment by tambakoo** [comment]
@palkan Any update on how to install anycable-go on a linux. I have an ec2 machine where I'll need this.

**Comment by Envek** [comment]
@tambakoo why not just download a precompiled binary?
```sh
curl -fsSL https://github.com/anycable/anycable-go/releases/download/v0.6.1/anycable-go-v0.6.1-linux-amd64 -o anycable-go
chmod +x anycable-go
```

**Comment by tambakoo** [comment]
@Envek 
`-bash-4.2$ sudo curl -fsSL https://github.com/anycable/anycable-go/releases/download/v0.6.1/anycable-go-v0.6.1-linux-amd64 -o anycable-go
-bash-4.2$ sudo chmod +x anycable-go
-bash-4.2$ anycable-go -v
-bash: anycable-go: command not found
-bash-4.2$
`
Am I making a syntactical error here ?

**Comment by Envek** [comment]
Use relative or absolute path to execute binaries not in your `$PATH` (current directory usually not included):
```sh
./anycable-go -v
```

**Comment by tambakoo** [comment]
Whoa! @Envek it just worked! Thanks.
