### ISSUE TITLE
Сообщение доставлено?

### ISSUE THREAD

**Issue by alekseyl** [anycable/anycable-go#36]
есть какой-то более лаконичный способ навскидку получения информации о доставленности/недоставленности сообщения на клиента? Кроме подтверждения с клиента через вызов самописной функции. 

Из кода я так понял, что сбой при отправке сообщения не нотифицируется никуда, получается что если произошел сбой при отправке на клиента, то сообщение из очереди редиса просто исчезнет, а сам код рубишный об этом не узнает?

**Comment by palkan** [comment]
> есть какой-то более лаконичный способ навскидку получения информации о доставленности/недоставленности сообщения на клиента

нет, без подтверждения на уровне приложения никак не получится; даже если сервер успешно отправит данные клиенту, нет гарантии, что они дойдут (клиент можно просто отключиться или сеть пропасть).

> получается что если произошел сбой при отправке на клиента, то сообщение из очереди редиса просто исчезнет

а в редисе по сути никакой очереди сейчас нет, сообщения нигде не хранятся, просто сразу отправляются всем подписчикам

в общем, гарантии доставки ни Action Cable, ни AnyCable не дают; её можно делать только на уровне приложения

в перспективе я рассматриваю возможность _восстановления_ при коротких разрывах (то есть при переподключении клиент получает все пропущенные сообщения и все подписки сохраняются); но это уже требует небольшие изменения протокола и, как следствие, переписывание клиентской части

**Comment by alekseyl** [comment]
спс. я уже и так начал делать версию лайт для построения отказоустойчивости. В зависимости от объемов кода или сделаю гемом, или просто небольшую заметочку с кодом напишу.
