### ISSUE TITLE
Anycable.broadcast не работает!

### ISSUE THREAD

**Issue by alekseyl** [anycable/anycable-go#39]
**AnyCable-Go version: 0.6.0.preview5**

**AnyCable gem version: anycable-rails: 0.5.3**

Не работает Anycable.broadcast.

    Anycable.broadcast( stream_id_for(recipient), {test: { broadcast: :failed! } } )

эникейбл-го выдает ошибку: 

context=node Failed to parse pubsub message '{"stream":"msgs:2","data":{"test":{"broadcast":"failed!"}}}' with error: json: cannot unmarshal object into Go struct field StreamMessage.data of type string

Трансмит работает нормально и клиент получает сообщение нормально распарсированное. 

Если попытаться отправить строку ошибки нет, но опять же ничего не приходит.

**Comment by alekseyl** [comment]
redis 4.0.1, хотя вряд ли его версия влияет.

**Comment by palkan** [comment]
Нужно использовать `ActionCable.server.broadcast`, он как раз конвертирует сообщение в json и уже его отправляет в `Anycable.broadcast`.

**Comment by alekseyl** [comment]
Thanx! 
+Была у меня ошибка тоже поэтому строки не отправлялись, хотя я пробовал.
