### ISSUE TITLE
Example systemd file

### ISSUE THREAD

**Issue by kernow** [anycable/anycable-go#51]
Are there any example systemd files available? Or best practice examples of running on ubuntu (16.04), I'm struggling to get the server running when using systemd.

Thanks

**Comment by Envek** [comment]
Example of systemd unit for anycable-go:

```ini
[Unit]
Description=AnyCable WebSocket Server
After=network.target

[Service]
Type=simple
ExecStart=/path/to/anycable-go # Please set it to the place where you've saved anycable-go binary
Restart=always
# User=somerestricteduser
# Group=somerestricteduser
# Environment=ANYCABLE_HOST=localhost
# Environment=ANYCABLE_PORT=8080
# Environment=ANYCABLE_PATH=/cable
# Environment=ANYCABLE_REDIS_URL=redis://localhost:6379/5
# Environment=ANYCABLE_REDIS_CHANNEL=__anycable__
# Environment=ANYCABLE_RPC_HOST=localhost:50051

[Install]
WantedBy=multi-user.target
```

 1. Place it to `/etc/systemd/system/anycable-go.service`
 2. Reload configuration: `sudo systemctl daemon-reload`
 3. Start service: `sudo systemctl start anycable-go`
 4. See how it runs: `sudo systemctl status anycable-go`

**Comment by Envek** [comment]
Also you can always generate systemd unit to run any binary with [pleaserun] gem (highly recommended!)

[pleaserun]: https://github.com/jordansissel/pleaserun "An attempt to abstract this init script madness."

**Comment by kernow** [comment]
Thanks @Envek very helpful

**Comment by palkan** [comment]
@Envek could you please add this to the docs? (https://github.com/anycable/docs.anycable.io)
