### ISSUE TITLE
Healthcheck

### ISSUE THREAD

**Issue by kernow** [anycable/anycable-go#52]
Hi,

Are there any plans to implement a healthcheck for the anycable-go websocket server similar to the anycable gem? We are setting this up behind an AWS application load balancer which only supports http healthchecks.

Thanks

**Comment by palkan** [comment]
@kernow Yep, that's the feature we definitely want to add) Stay tuned

**Comment by palkan** [comment]
@kernow Released https://github.com/anycable/anycable-go/releases/tag/v0.6.1

**Comment by kernow** [comment]
@palkan @sponomarev only just got to installing this after the xmas break, thanks for implementing so quickly!! Working for me with AWS load balancers 👍 

Ah, ha, ha, ha, stayin' alive, stayin' alive.
