### ISSUE TITLE
connection stress test outcomes

### ISSUE THREAD

**Issue by jjhesk** [anycable/anycable-go#58]
I would like to ask what is the test figures for these outcomes

1. connection with 1000 concurrent connections with open 65540 open files and unlimited processes
2. operate over 10 hours
3. see any race detections?

**Comment by palkan** [comment]
Hi @jjhesk!

Need some clarification.

> 1. connection with 1000 concurrent connections with open 65540 open files and unlimited processes

Do you mean that you have a server with open files limit set to 65540 (via `ulimit` or `sysctl`), no limits on the number of processes.
One `anycable-go` app instance is running and 1000 clients are connected, right?

> 2\. operate over 10 hours

All the clients are stay connected for 10 hours? Or there could be different clients, connecting and disconnecting, but on average 1k at a time?

What about the number of incoming/outgoing messages (or the number of broadcasted messages)?

> 3\. see any race detections?

Could you elaborate?

**Comment by jjhesk** [comment]
1. given 32 core, 16GB ram, intel, ubuntu 18.0.1
2. stay connected for 10 hrs with some operations maybe 1% of the operations. 
3.  yea, any race detections and the number of detects

**Comment by palkan** [comment]
Closed as stale
