### ISSUE TITLE
Make "Auth Failed" easier to debug

### ISSUE THREAD

**Issue by jurajmasar** [anycable/anycable-go#7]
Thank you @palkan for this wonderful gem.

I'm trying to deploy Anycable with Anycable-go using Dokku (docker-based deployment scripts utilizing Heroku buildpacks). While Anycable-go worked for me out of box on localhost, I'm having troubles making it work on production, behind Nginx.

When I run anycable-go using 
`/app/bin/anycable-go/anycable-go-0.4.1-linux-amd64 -redis=[redacted] -rpc=localhost:50051 -addr=0.0.0.0:8080 -log=true`

I get

```
Ping interval 3s
Running AnyCable websocket server v0.4.1 on 0.0.0.0:8080 at /cable
Disconnect rate 10ms
anycable: subscribe 1
```

When the first request comes in (through Nginx), I see 

```
Auth
Auth Failed
```

Can we please make this error message more descriptive and/or include tips for troubleshooting? I've tried running the RPC on `0.0.0.0:50051` as well as setting `SKIP_AUTH=1` in environmental variable.

I'll be grateful for any suggestions. Thank you.

**Comment by palkan** [comment]
Hi, Juraj!

Could you, please, show me your nginx configuration, Connection `#connect` method (or how do you authenticate connections) and also RPC server logs (run it with `ANYCABLE_DEBUG=1` to get more verbose logs)?

**Comment by jurajmasar** [comment]
Hi @palkan, thanks for your reply - looking into `Connection#connect` I was able to identify an issue. 

I've originally thought that there was some kind of authentication problem between the Go instance and the RPC server. I suggest making "Auth Failed" more descriptive. :-)

Thanks again!

**Comment by palkan** [comment]
Fixed. Now we log exceptions received from RPC.

**Comment by jurajmasar** [comment]
Thank you, @palkan!
