### ISSUE TITLE
Consider updating base image from `scratch` to `alpine`

### ISSUE THREAD

**Issue by FX-HAO** [anycable/anycable-go#72]
`scratch` does not contain `/bin/sh`, or anything else. I can't run it with `docker run -it --entrypoint=/bin/sh anycable/anycable-go:v0.6.2 -c "--redis-url=redis://localhost:6379/5 --http-health-port=80 --rpc-host=0.0.0.0:50001"` and use `docker exec -it anycable /bin/sh` to get ssh into the running container.

**Comment by palkan** [comment]
The latest release alpine image has been published: https://hub.docker.com/r/anycable/anycable-go/tags

Future releases will also have alpine versions.
