### ISSUE TITLE
Env Support for Anycable-go

### ISSUE THREAD

**Issue by dmcrorieGIT** [anycable/anycable-go#80]
I was wondering if we could get a version of anycable which supports env variables? (https://github.com/iij/mruby-env). I would make a branch and do a pull request myself, but I don't have the proper permissions to do so. To make such a version, all one would need to do is add the line `conf.gem :github => 'iij/mruby-env'` to the `build_config.rb` file. My organization would benefit tremendously from our anycable-go having access to env variables, so if this is at all possible it would be greatly appreciated!

-Dustin McRorie

**Comment by palkan** [comment]
As a quick fix I suggest including `mruby-env`  into `mrb` builds.
Ideally, I want to make it possible to use custom mruby builds without rebuilding `anycable-go` itself. That's the plan for the future (not the nearest one though).

**Comment by dmcrorieGIT** [comment]
Excellent, thanks for letting me know! That would be a very sleek way of doing it in the future as well. Here is a link to my pull request which includes the change: https://github.com/anycable/anycable-go/pull/81 also, is it possible that you could compile the binaries on your end? Our machines are all on macos, we're running into some errors when trying to compile some of them, specifically the `anycable-go-v0.6.X-mrb-linux-amd64`. Thanks in advance! 🙏

**Comment by sponomarev** [comment]
> is it possible that you could compile the binaries on your end?

They will be compiled automatically on CI once the PR is merged and the new version is released.

**Comment by palkan** [comment]
Added in #81 and released in [0.6.4](https://github.com/anycable/anycable-go/releases/tag/v0.6.4).
