### ISSUE TITLE
HSTS support

### ISSUE THREAD

**Issue by thatandyrose** [anycable/anycable-go#85]
hi guys,

We've really tried googling this answer to no avail. Either our googling skills suck... or, actually probably that :-)

We're using Anycable-go and we want to make sure our socket connections implement HSTS (we recently had a penetration test done and that came up as a minor issue).

How do we do this when using anycable go?

thanks!

**Comment by sponomarev** [comment]
Hey @thatandyrose, thanks for the great question!

Ideally, you should set NGINX or any kind of reverse proxy to set those headers and terminate SSL connection. I hope this article would be helpful https://www.nginx.com/blog/http-strict-transport-security-hsts-and-nginx/
