### ISSUE TITLE
Totally different environments seem to send messages to the same one?

### ISSUE THREAD

**Issue by vitobotta** [anycable/anycable-go#90]
Hi, I am using AnyCable in Rails and have installed AnyCable Go in Kuberentes with the helm chart. 
I have three totally different environments for my app (dev/staging/prod) so I have three different AnyCable-Go deployments, each pointing to the relevant environment of the Rails app for the RPC service. I think that everything is configured correctly in that the services etc have all different namespaces and names and they are pointing to the right things for each environment. However, if I have three tabs for my app in my browser, one for each environment, and with the Rails console I broadcast a message to one environment, ALL the three environments receive the same message, even though they are connecting to different domains each of which is connecting to a different RPC host.

The only thing in common is the single Redis instance, but I am specifying different database numbers in the Redis URLs. Can this explain the problem? Can multiple AnyCable instances share the same Redis instances with different databases?

What could be causing a message sent to one instance of AnyCable being received by the others as well?

I'm stuck, so thanks a lot in advance for any help! :)

**Comment by vitobotta** [comment]
I tried setting different Redis channels but now no messages are received by any instance.

**Comment by vitobotta** [comment]
I found the `--redis-channel` parameter for anycable-rails. I am testing with an environment only now. Both anycable-go and anycable-rails are now using the same Redis channel (confirmed in the logs), and when the browser establishes the connection I can see something in the console (I am just doing a console.log on connection). However if I broadcast messages from a Rails console they don't reach the browser. Do I need to specify the Redis channel somewhere else?

**Comment by sponomarev** [comment]
> Can multiple AnyCable instances share the same Redis instances with different databases?

Unfortunately, [Redis PUBSUB doesn't work with database numbers](https://redis.io/topics/pubsub#database-amp-scoping). _Publishing on db 10, will be heard by a subscriber on db 1._

The only way to share the single Redis instance is to use unique Redis channel names per environment. 

In order to do that you need to set the `redis_channel` option [for AnyCable Go ](https://docs.anycable.io/#/anycable-go/getting_started) and [RPC server](https://docs.anycable.io/#/ruby/configuration?id=configuration)

**Comment by vitobotta** [comment]
Hi @sponomarev thanks for the confirmation about the dbs. Both anycable-go and the `bundle exec anycable --redis-channel xxx` are using the same channel now, but messages I broadcast from the Rails console don't reach the browser. Any idea? Thanks

**Comment by sponomarev** [comment]
> However if I broadcast messages from a Rails console they don't reach the browser.

Rails console doesn't know anything about `--redis-channel` option, but you can set it in `config/anycable.yml`.

**Comment by sponomarev** [comment]
Probably, `ANYCABLE_REDIS_CHANNEL` env variable could also work.

**Comment by vitobotta** [comment]
I set redis_channel in anycable.yml and it worked, thanks! I'm gonna try with the other envs now. Thanks a lot again

**Comment by sponomarev** [comment]
@vitobotta Feel free to reopen the issue in case of any further questions
