### ISSUE TITLE
Consider using alpine:latest instead of edge

### ISSUE THREAD

**Issue by ericmatte** [anycable/anycable-go#92]
Hi,

Following the warning on [Alpine Linux wiki page](https://wiki.alpinelinux.org/wiki/Edge):
> "edge" is under constant development so be careful using it in production. It is possible that bugs in "edge" could cause data loss or could break your system.

I think it would be a great idea to use the `alpine:latest` version (or a fixed version of alpine), as the `edge` version is not suitable for production environment.

**Comment by sponomarev** [comment]
@ericmatte Thanks, this is a valid point. Will you provide a PR while we're waiting for @palkan's confirmation?

**Comment by ericmatte** [comment]
@sponomarev, sure! Here we go: https://github.com/anycable/anycable-go/pull/93
