### ISSUE TITLE
CORS config

### ISSUE THREAD

**Issue by hexagen48** [anycable/anycable-go#94]
We are using anycable - go as an WS server for our rails app in api only mode.
Is it possible to configure CORS in this case? Or it should be done maybe at nginx level?

Thanks.

**Comment by sponomarev** [comment]
Hey @hexagen48! What is the reason you want to set CORS headers for AnyCable?  CORS is not applicable to WebSocket data. 

As for the Rails API, it's out of the scope for these repository topics, but there are plenty of options including setting CORS headers on a balancer layer or on the Rails app itself.

**Comment by hexagen48** [comment]
Thanks for the answer @sponomarev
