### ISSUE TITLE
Allow same origin as Host configuration is always failing because HTTP_HOST is always blank

### ISSUE THREAD

**Issue by SakthiGurunathan07** [anycable/anycable-go#96]
**AnyCable-Go version:**
 1.0.0 preview

**AnyCable gem version:**
 1.0.0 preview

### What did you do?
 I have anycable-go server running behind a Nginx reverse proxy. From Nginx reverse proxy, I set the headers for Host. I ran the go server listening to 8080 port and have configured to fetch headers host, cookie and origin. My aim is to pass both host and origin as part of the header so that allow_same_origin_as_host configuration should succeed in allow_request_origin? (Forgery protection check) method.

 **Ngnix configuration**

 location /cable {
    proxy_pass http://localhost:8080;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header Http_AnyCable_Host $http_host;
  }

**Command to start go server**
  anycable-go --headers=cookie,origin,host,http_anycable_host --redis_url=redis://localhost:6379/4 --redis_channel=anycable-development --host=localhost --port=8080 --log_level=debug

**Anycable go server log**

 D 2020-04-17T21:12:46.053Z context=node sid=9Pm42H7tho_lyeZDEBhnHd Disconnect {"__ltags__":["Member ID: XX"],"member":"Z2lkOi8vXXb2XX51cy1tZW50b3ItYmFzZS9NZW1iZXIvNTA"} /cable map[REMOTE_ADDR:127.0.0.1 cookie: current_locale=en;client_time_difference=-836 **host: http_anycable_host:abc.something.com origin:https://abc.something.com**] [{"channel":"ChatChannel","context_id":XXXXX}]

### What did you expect to happen?
 But the allow_same_origin_as_host check failed because HTTP_HOST value is always blank. If I try to send the $http_host value in some other custom header say "http_anycable_host", then I could see its (HTTP_ANYCABLE_HOST) value in the request headers.

 In any cable go server log, I couldn't find the value for the host header.

 Could you please help me understand why the HTTP_HOST value is always blank?
@palkan @Envek @sponomarev

**Comment by palkan** [comment]
As we can see from the `anycable-go` logs, the `Host` header is not provided in the request or empty.

Shouldn't there be `$host` instead of the `$http_host`? See https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/#headers and https://nginx.org/en/docs/http/ngx_http_core_module.html?#variables

**Comment by SakthiGurunathan07** [comment]
@palkan  Thanks for your reply. I tried with $host and $http_host, host header is always coming as blank. Even I tried hardcoding the host header value in nginx but still no luck. The workaround I have is to set a custom proxy header say "ANYCABLE_HOST" and enable the custom header in the go server and put a patch for 'allow_request_origin?' method to use ANYCABLE_HOST instead of HOST for allow_same_origin_as_host configuration.
Please let me know if you have faced any issue of that sort ?

**Comment by palkan** [comment]
This has been fixed in 1.0.0.rc1. The problem was that anycable-go only passed the path part of the connection url, not the full url.
No need to specify any additional headers.
